sudo: false
language: python
matrix:
  include:
    - dist: trusty
      python: "3.6"
      env: TOXENV=py36-courier_released
      after_success: coveralls
    - dist: xenial
      python: "3.7"
      env: TOXENV=py37-courier_released
      after_success: coveralls
    - dist: trusty
      python: "3.6"
      env: TOXENV=py36-courier_master
      after_success: coveralls
    - dist: xenial
      python: "3.7"
      env: TOXENV=py37-courier_master
      after_success: coveralls
    - dist: xenial
      python: "3.7"
      env: TOXENV=flake8
before_install:
  - sudo apt-get install -y rpm  # for rpm-py-installer (koji requirement)
install: pip install tox-travis coveralls
script: tox
