sudo: false
language: python
matrix:
  include:
    - dist: trusty
      python: "3.6"
    - dist: xenial
      python: "3.7"
install: pip install tox-travis coveralls
script: tox
after_success: coveralls
